apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-svc
  labels:
    tier: devops
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.webhook.server.port }}
    targetPort: {{ .Values.webhook.server.targetPort }}
  selector:
    tier: devops
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
    release: {{ .Release.Name }}
