apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    tier: devops
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
    release: {{ .Release.Name }}